import type { Metadata } from "next";
import { Montserrat as Inter } from "next/font/google";
import { Flip, ToastContainer } from 'react-toastify';

import { AuthProvider } from "@/provider/auth-provider";
import { MainFooter } from "@/components/shared/footer";

import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";


// App Font
const inter = Inter({ subsets: ["latin"] });

// App metadata
export const metadata: Metadata = {
    title: "QuickList",
    description: "Generated by create next app",
};


export default function RootLayout({ children }: TLayout) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    {children}
                    <MainFooter />
                    <ToastContainer
                        autoClose={5000}
                        position="bottom-right"
                        theme="dark"
                        closeOnClick
                        stacked
                        transition={Flip}
                    />
                </AuthProvider>
            </body>
        </html>
    );
}
